include: https://api.choerodon.com.cn/devops/v1/projects/261899051275677696/ci_contents/pipelines/e387fb62-de82-4630-8e46-f18d64643623/content.yaml
#include: https://api.choerodon.com.cn/devops/v1/projects/1529/ci_contents/pipelines/f558f8ec-461f-408e-8a8e-bbd113e0dcb9/content.yaml

